# Generated by Django 4.1 on 2022-10-01 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
